pokemon(victini, 494).
pokemon(snivy, 495).
pokemon(servine, 496).
pokemon(serperior, 497).
pokemon(tepig, 498).
pokemon(pignite, 499).
pokemon(emboar, 500).
pokemon(oshawott, 501).
pokemon(dewott, 502).
pokemon(samurott, 503).
pokemon(patrat, 504).
pokemon(watchog, 505).
pokemon(lillipup, 506).
pokemon(herdier, 507).
pokemon(stoutland, 508).
pokemon(purrloin, 509).
pokemon(liepard, 510).
pokemon(pansage, 511).
pokemon(simisage, 512).
pokemon(pansear, 513).
pokemon(simisear, 514).
pokemon(panpour, 515).
pokemon(simipour, 516).
pokemon(munna, 517).
pokemon(musharna, 518).
pokemon(pidove, 519).
pokemon(tranquill, 520).
pokemon(unfezant, 521).
pokemon(blitzle, 522).
pokemon(zebstrika, 523).
pokemon(roggenrola, 524).
pokemon(boldore, 525).
pokemon(gigalith, 526).
pokemon(woobat, 527).
pokemon(swoobat, 528).
pokemon(drilbur, 529).
pokemon(excadrill, 530).
pokemon(audino, 531).
pokemon(timburr, 532).
pokemon(gurdurr, 533).
pokemon(conkeldurr, 534).
pokemon(tympole, 535).
pokemon(palpitoad, 536).
pokemon(seismitoad, 537).
pokemon(throh, 538).
pokemon(sawk, 539).
pokemon(sewaddle, 540).
pokemon(swadloon, 541).
pokemon(leavanny, 542).
pokemon(venipede, 543).
pokemon(whirlipede, 544).
pokemon(scolipede, 545).
pokemon(cottonee, 546).
pokemon(whimsicott, 547).
pokemon(petilil, 548).
pokemon(lilligant, 549).
pokemon(basculin, 550).
pokemon(sandile, 551).
pokemon(krokorok, 552).
pokemon(krookodile, 553).
pokemon(darumaka, 554).
pokemon(darmanitan, 555).
pokemon(maractus, 556).
pokemon(dwebble, 557).
pokemon(crustle, 558).
pokemon(scraggy, 559).
pokemon(scrafty, 560).
pokemon(sigilyph, 561).
pokemon(yamask, 562).
pokemon(cofagrigus, 563).
pokemon(tirtouga, 564).
pokemon(carracosta, 565).
pokemon(archen, 566).
pokemon(archeops, 567).
pokemon(trubbish, 568).
pokemon(garbodor, 569).
pokemon(zorua, 570).
pokemon(zoroark, 571).
pokemon(minccino, 572).
pokemon(cinccino, 573).
pokemon(gothita, 574).
pokemon(gothorita, 575).
pokemon(gothitelle, 576).
pokemon(solosis, 577).
pokemon(duosion, 578).
pokemon(reuniclus, 579).
pokemon(ducklett, 580).
pokemon(swanna, 581).
pokemon(vanillite, 582).
pokemon(vanillish, 583).
pokemon(vanilluxe, 584).
pokemon(deerling, 585).
pokemon(sawsbuck, 586).
pokemon(emolga, 587).
pokemon(karrablast, 588).
pokemon(escavalier, 589).
pokemon(foongus, 590).
pokemon(amoonguss, 591).
pokemon(frillish, 592).
pokemon(jellicent, 593).
pokemon(alomomola, 594).
pokemon(joltik, 595).
pokemon(galvantula, 596).
pokemon(ferroseed, 597).
pokemon(ferrothorn, 598).
pokemon(klink, 599).
pokemon(klang, 600).
pokemon(klinklang, 601).
pokemon(tynamo, 602).
pokemon(eelektrik, 603).
pokemon(eelektross, 604).
pokemon(elgyem, 605).
pokemon(beheeyem, 606).
pokemon(litwick, 607).
pokemon(lampent, 608).
pokemon(chandelure, 609).
pokemon(axew, 610).
pokemon(fraxure, 611).
pokemon(haxorus, 612).
pokemon(cubchoo, 613).
pokemon(beartic, 614).
pokemon(cryogonal, 615).
pokemon(shelmet, 616).
pokemon(accelgor, 617).
pokemon(stunfisk, 618).
pokemon(mienfoo, 619).
pokemon(mienshao, 620).
pokemon(druddigon, 621).
pokemon(golett, 622).
pokemon(golurk, 623).
pokemon(pawniard, 624).
pokemon(bisharp, 625).
pokemon(bouffalant, 626).
pokemon(rufflet, 627).
pokemon(braviary, 628).
pokemon(vullaby, 629).
pokemon(mandibuzz, 630).
pokemon(heatmor, 631).
pokemon(durant, 632).
pokemon(deino, 633).
pokemon(zweilous, 634).
pokemon(hydreigon, 635).
pokemon(larvesta, 636).
pokemon(volcarona, 637).
pokemon(cobalion, 638).
pokemon(terrakion, 639).
pokemon(virizion, 640).
pokemon(tornadus, 641).
pokemon(thundurus, 642).
pokemon(reshiram, 643).
pokemon(zekrom, 644).
pokemon(landorus, 645).
pokemon(kyurem, 646).
pokemon(keldeo, 647).
pokemon(meloetta, 648).
pokemon(genesect, 649).

tipo(victini, fogo).
tipo(snivy, grama).
tipo(servine, grama).
tipo(serperior, grama).
tipo(tepig, fogo).
tipo(pignite, fogo).
tipo(emboar, fogo).
tipo(oshawott, agua).
tipo(dewott, agua).
tipo(samurott, agua).
tipo(patrat, normal).
tipo(watchog, normal).
tipo(lillipup, normal).
tipo(herdier, normal).
tipo(stoutland, normal).
tipo(purrloin, sombrio).
tipo(liepard, sombrio).
tipo(pansage, grama).
tipo(simisage, grama).
tipo(pansear, fogo).
tipo(simisear, fogo).
tipo(panpour, agua).
tipo(simipour, agua).
tipo(munna, psiquico).
tipo(musharna, psiquico).
tipo(pidove, normal).
tipo(tranquill, normal).
tipo(unfezant, normal).
tipo(blitzle, eletrico).
tipo(zebstrika, eletrico).
tipo(roggenrola, pedra).
tipo(boldore, pedra).
tipo(gigalith, pedra).
tipo(woobat, psiquico).
tipo(swoobat, psiquico).
tipo(drilbur, terra).
tipo(excadrill, terra).
tipo(audino, normal).
tipo(timburr, lutador).
tipo(gurdurr, lutador).
tipo(conkeldurr, lutador).
tipo(tympole, agua).
tipo(palpitoad, agua).
tipo(seismitoad, agua).
tipo(throh, lutador).
tipo(sawk, lutador).
tipo(sewaddle, inseto).
tipo(swadloon, inseto).
tipo(leavanny, inseto).
tipo(venipede, inseto).
tipo(whirlipede, inseto).
tipo(scolipede, inseto).
tipo(cottonee, grama).
tipo(whimsicott, grama).
tipo(petilil, grama).
tipo(lilligant, grama).
tipo(basculin, agua).
tipo(sandile, terra).
tipo(krokorok, terra).
tipo(krookodile, terra).
tipo(darumaka, fogo).
tipo(darmanitan, fogo).
tipo(maractus, grama).
tipo(dwebble, inseto).
tipo(crustle, inseto).
tipo(scraggy, sombrio).
tipo(scrafty, sombrio).
tipo(sigilyph, psiquico).
tipo(yamask, fantasma).
tipo(cofagrigus, fantasma).
tipo(tirtouga, agua).
tipo(carracosta, agua).
tipo(archen, pedra).
tipo(archeops, pedra).
tipo(trubbish, venenoso).
tipo(garbodor, venenoso).
tipo(zorua, sombrio).
tipo(zoroark, sombrio).
tipo(minccino, normal).
tipo(cinccino, normal).
tipo(gothita, psiquico).
tipo(gothorita, psiquico).
tipo(gothitelle, psiquico).
tipo(solosis, psiquico).
tipo(duosion, psiquico).
tipo(reuniclus, psiquico).
tipo(ducklett, agua).
tipo(swanna, agua).
tipo(vanillite, gelo).
tipo(vanillish, gelo).
tipo(vanilluxe, gelo).
tipo(deerling, normal).
tipo(sawsbuck, normal).
tipo(emolga, eletrico).
tipo(karrablast, inseto).
tipo(escavalier, inseto).
tipo(foongus, grama).
tipo(amoonguss, grama).
tipo(frillish, agua).
tipo(jellicent, agua).
tipo(alomomola, agua).
tipo(joltik, inseto).
tipo(galvantula, inseto).
tipo(ferroseed, grama).
tipo(ferrothorn, grama).
tipo(klink, metal).
tipo(klang, metal).
tipo(klinklang, metal).
tipo(tynamo, eletrico).
tipo(eelektrik, eletrico).
tipo(eelektross, eletrico).
tipo(elgyem, psiquico).
tipo(beheeyem, psiquico).
tipo(litwick, fantasma).
tipo(lampent, fantasma).
tipo(chandelure, fantasma).
tipo(axew, dragao).
tipo(fraxure, dragao).
tipo(haxorus, dragao).
tipo(cubchoo, gelo).
tipo(beartic, gelo).
tipo(cryogonal, gelo).
tipo(shelmet, inseto).
tipo(accelgor, inseto).
tipo(stunfisk, terra).
tipo(mienfoo, lutador).
tipo(mienshao, lutador).
tipo(druddigon, dragao).
tipo(golett, terra).
tipo(golurk, terra).
tipo(pawniard, sombrio).
tipo(bisharp, sombrio).
tipo(bouffalant, normal).
tipo(rufflet, normal).
tipo(braviary, normal).
tipo(vullaby, sombrio).
tipo(mandibuzz, sombrio).
tipo(heatmor, fogo).
tipo(durant, inseto).
tipo(deino, sombrio).
tipo(zweilous, sombrio).
tipo(hydreigon, sombrio).
tipo(larvesta, inseto).
tipo(volcarona, inseto).
tipo(cobalion, metal).
tipo(terrakion, pedra).
tipo(virizion, grama).
tipo(tornadus, voador).
tipo(thundurus, eletrico).
tipo(reshiram, dragao).
tipo(zekrom, dragao).
tipo(landorus, terra).
tipo(kyurem, dragao).
tipo(keldeo, agua).
tipo(meloetta, normal).
tipo(genesect, inseto).

TiposUnicos = [agua, dragao, eletrico, fantasma, fogo, gelo, grama, inseto, lutador, metal, normal, pedra, psiquico, sombrio, terra, venenoso, voador].

evolui(snivy, servine).
evolui(servine, surperior).
evolui(tepig, pignite).
evolui(pignite, emboar).
evolui(oshawott, dewott).
evolui(dewott, samurott).
evolui(patrat, watchog).
evolui(lillipup, herdier).
evolui(herdier, stoutland).
evolui(purrloin, liepard).
evolui(pansage, simisage).
evolui(pansear, simisear).
evolui(panpour, simipour).
evolui(munna, musharna).
evolui(pidove, tranquill).
evolui(tranquill, unfezant).
evolui(blitzle, zebstrika).
evolui(roggenrola, boldore).
evolui(boldore, gigalith).
evolui(woobat, swoobat).
evolui(drilbur, excadrill).
evolui(timburr, gurdurr).
evolui(gurdurr, conkeldurr).
evolui(tympole, palpitoad).
evolui(palpitoad, seismitoad).
evolui(sewaddle, swadloon).
evolui(swadloon, leavanny).
evolui(venipede, whirlipede).
evolui(whirlipede, scolipede).
evolui(cottonee, whimsicott).
evolui(petilil, lilligant).
evolui(sandile, krokorok).
evolui(krokorok, krookodile).
evolui(darumaka, darmanitan).
evolui(dwebble, crustle).
evolui(scraggy, scrafty).
evolui(yamask, cofagrigus).
evolui(tirtouga, carracosta).
evolui(archen, archeops).
evolui(trubbish, garbodor).
evolui(zorua, zoroark).
evolui(minccino, cinccino).
evolui(gothita, gothorita).
evolui(gothorita, gothitelle).
evolui(solosis, duosion).
evolui(duosion, reuniclus).
evolui(ducklett, swanna).
evolui(vanillite, vanillish).
evolui(vanillish, vanilluxe).
evolui(deerling, sawsbuck).
evolui(karrablast, escavalier).
evolui(foongus, amoonguss).
evolui(frillish, jellicent).
evolui(joltik, galvantula).
evolui(ferroseed, ferrothorn).
evolui(klink, klang).
evolui(klang, klinklang).
evolui(tynamo, eelektrik).
evolui(eelektrik, eelektross).
evolui(elgyem, beheeyem).
evolui(litwick, lampent).
evolui(lampent, chandelure).
evolui(axew, fraxure).
evolui(fraxure, haxorus).
evolui(cubchoo, beartic).
evolui(shelmet, accelgor).
evolui(mienfoo, mienshao).
evolui(golett, golurk).
evolui(pawniard, bisharp).
evolui(rufflet, braviary).
evolui(vullaby, mandibuzz).
evolui(deino, zweilous).
evolui(zweilous, hydreigon).
evolui(larvesta, volcarona).

vantagem(metal, fada).
vantagem(metal, gelo).
vantagem(metal, pedra).
vantagem(agua, fogo).
vantagem(agua, pedra).
vantagem(agua, terra).
vantagem(dragao, dragao).
vantagem(eletrico, voador).
vantagem(eletrico, agua).
vantagem(fada, sombrio).
vantagem(fada, dragao).
vantagem(fada, lutador).
vantagem(fatasma, fantasma).
vantagem(fantasma,psiquico).
vantagem(fogo, metal).
vantagem(fogo, gelo).
vantagem(fogo, inseto).
vantagem(fogo, grama).
vantagem(gelo, dragao).
vantagem(gelo, grama).
vantagem(gelo, terra).
vantagem(gelo, voador).
vantagem(inseto, grama).
vantagem(inseto, psiquico).
vantagem(inseto, sombrio).
vantagem(lutador, metal).
vantagem(lutador, gelo).
vantagem(lutador, normal).
vantagem(lutador, pedra).
vantagem(lutador, sombrio).
vantagem(pedra, fogo).
vantagem(pedra, gelo).
vantagem(pedra, inseto).
vantagem(pedra, voador).
vantagem(grama, agua).
vantagem(grama, terra).
vantagem(grama, pedra).
vantagem(psiquico, lutador).
vantagem(psiquico, venenoso).
vantagem(sombrio, fantasma).
vantagem(sombrio, psiquico).
vantagem(terra, metal).
vantagem(terra, eletrico).
vantagem(terra, fogo).
vantagem(terra, pedra).
vantagem(terra, venenoso).
vantagem(venenoso, fada).
vantagem(venenoso, grama).
vantagem(voador, inseto).
vantagem(voador, lutador).
vantagem(voador, grama).